server:
  port: 8080
spring:
  application:
    name: "ms-commands"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb+srv://cronjobuser:AppClave123@clustertraining.e3r17.mongodb.net/ms-commands?retryWrites=true&w=majority"